server:
  port: 8080
  servlet:
    context-path: "/"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whitelist?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: ""
rcon:
  host: localhost
  port: 25575
  password: ""
time:
  token: 720
  vcode: 60
aliyun:
  access-key-id: ""
  access-key-secret: ""
  mail-html: |
    <!DOCTYPE html PUBLIC"-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3
    .org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml ns="http://www.w3.org/1999/xhtml"style="
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; 
    font-size: 14px; margin: 0;" ><head> <meta name="viewport" content="width=device-width"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><title>重置密码</title><style type="text/css">
    img {
    max-width: 100%;
    }
      body {
    -webkit-font-smoothing: antialiased;
    -webkit-text-size-adjust: none;
    width: 100% !important;
    height: 100%;
    line-height: 1.6em;
    }
      body {
    background-color: #f6f6f6;
    }
      @media only screen and(max-width:640px) {
      body {
    padding: 0 !important;
    }
      h1 {
    font-weight: 800 !important;
    margin: 20px 0 5px !important;
    }
      h2 {
    font-weight: 800 !important;
    margin: 20px 0 5px !important;
    }
      h3 {
    font-weight: 800 !important;
    margin: 20px 0 5px !important;
    }
      h4 {
    font-weight: 800 !important;
    margin: 20px 0 5px !important;
    }
      h1 {
    font-size: 22px !important;
    }
      h2 {
    font-size: 18px !important;
    }
      h3 {
    font-size: 16px !important;
    }
      .container {
    padding: 0 !important;
    width: 100% !important;
    }
      .content {
    padding: 0 !important;
    }
      .content-wrap {
    padding: 10px !important;
    }
      .invoice {
    width: 100% !important;
    }
    }
    </style></head><bodyitemscopeitemtype="http://schema.org/EmailMessage"style=" font-family: 
    'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; 
    -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; 
    height: 100%; line-height: 1.6em; background-color: #f6f6f6; margin: 0;" 
    bgcolor="#f6f6f6"><tableclass="body-wrap"style=" font-family: 'Helvetica Neue', Helvetica, 
    Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background-color: 
    #f6f6f6; margin: 0;" bgcolor="#f6f6f6"><trstyle=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" ><td style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td><td class="container"width="600"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto;" valign="top"><divclass="content"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 20px;" > <tableclass="main"width="100%"cellpadding="0"cellspacing="0"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background-color: #fff; margin: 0; border: 1px solid #e9e9e9;"bgcolor="#fff"><trstyle=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"> <td class="alert alert-warning"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; vertical-align: top; color: #fff; font-weight: 500; text-align: center; border-radius: 3px 3px 0 0; background-color: #2196f3; margin: 0; padding: 20px;" align="center"bgcolor="#FF9F00"valign="top">找回密码 - 五彩世界白名单自助申请系统</td></tr><trstyle=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"> <td class="content-wrap"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 20px;" valign="top"><tablewidth="100%"cellpadding="0"cellspacing="0"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" ><tr style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"> <td class="content-block"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">你好! <strongstyle=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">{name}</strong >： </td></tr><tr style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"> <td class="content-block"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">请点击下方按钮完成密码重设. 若不是您本人操作, 请忽略此邮件.</td></tr><trstyle=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"> <td class="content-block"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top"><a href="https://whitelist.jonjs.cn/resetPassword/{vcode}"class="btn-primary"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; color: #fff; text-decoration: none; line-height: 2em; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: capitalize; background-color: #2196f3; margin: 0; border-color: #2196f3; border-style: solid; border-width: 10px 20px;">重设密码</a > </td></tr><tr style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"> <td class="content-block"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">祝愿您天天开心.</td></tr></table></td></tr></table><divclass="footer"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; margin: 0; padding: 20px;" ><table width="100%"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"> <tr style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" > <tdclass="aligncenter content-block"style=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 12px; vertical-align: top; color: #999; text-align: center; margin: 0; padding: 0 0 20px;"align="center"valign="top">此邮件由系统自动发送, 请不要直接回复.</td></tr></table></div></div></td><tdstyle=" font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td></tr></table></body></html>"


